version: '3.8'

services:
  app:
    build: .
    image: learn-nestjs-app
    container_name: nest-docker
    ports:
      - "3000:3002"
    env_file:
      - .env.production.local
    depends_on:
      - db

  db:
    image: mariadb:10.6.16
    container_name: mariadb
    restart: always
    ports:
      - "3308:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "8080:80"

volumes:
  mariadb_data:


